---
abstract: 'download bugs from an RT queue and dump them as RDF'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RT::ClientX::GrabBugs
name: RT-ClientX-GrabBugs
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Getopt::ArgvFile: 0
  Getopt::Long: 0
  HTTP::Cookies: 0
  Module::Install::Admin::RDF: 0
  Moose: 2.00
  RDF::Trine: 0.130
  Web::Magic: 0.007
  autodie: 0
  namespace::autoclean: 0
  perl: 5.10.0
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RT-ClientX-GrabBugs
  homepage: https://metacpan.org/release/RT-ClientX-GrabBugs
  license: http://dev.perl.org/licenses/
version: 0.001
